#!/bin/bash
# ./bf-to-simp program.bf program.asm
#-Wl,-z,stack-size=4194304
gcc bf-simp/*.c
rc=$?
if [ $rc -ne 0 ]; then
    echo "Error building transpiler" 1>&2
    exit 1
fi
./a.out $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15}
rc=$?
if [ $rc -ne 0 ]; then
    echo "Transpilation finished with errors" 1>&2
    exit 1
fi