#!/bin/sh

# Before using this make sure you have installed the dependencies for your distro:
# Ubuntu: sudo apt install gcc-mingw-w64
# Arch: sudo pacman -S mingw-w64-gcc
if [[ ! -e "bin" ]]; then
    mkdir "bin"
fi

if [[ ! -e "bin/linux" ]]; then
    mkdir "bin/linux"
elif [[ ! -d "bin/linux" ]]; then
    echo "bin/linux already exists but is not a directory" 1>&2
fi

gcc Assembler/*.c -o bin/linux/asm
if [ $? -ne 0 ]; then
    echo "Error building linux assembler" 1>&2
    exit 1
fi
gcc Simulator/*.c -o bin/linux/sim -lX11 
if [ $? -ne 0 ]; then
    echo "Error building linux simulator" 1>&2
    exit 1
fi

echo "Compiled the project successfully!"