#!/bin/bash
dbg=""




if [[ $1 = "-h" ]]; then
    echo "Usage: ./nass <file.asm>        | Assemble and simulate the given file"
    echo "       ./nass -h                | Display this help message"
    echo "       ./nass -bf <file.bf>     | Compile brainfuck and run the generated code" 
    echo "       ./nass <file.asm> -c     | Clean up build and run directories" 
    echo "       ./nass <file.asm> -d     | Assemble and run assembly file with debug options" 
    exit 0
fi

if [[ $1 = "-bf" ]]; then
    wd=$(dirname $2)
    fn=$(basename $2)
    ./bf-to-simp $2 "$(echo $wd)/$(echo $fn).asm"
    if [ $? -ne 0 ]; then
        exit 1
    fi
    assembly="$(echo $wd)/$(echo $fn).asm"
else
    wd=$(dirname $1)
    fn=$(basename $1)
    assembly=$1
fi

if [[ $3 = "-c" ]] || [[ $2 = "-c" ]]; then
    rm -rf "$(echo $wd)/build"
    rm -rf "$(echo $wd)/run"
    echo "Cleaned up build and run directories"
    exit 0
fi

if [[ $3 = "-d" ]] || [[ $2 = "-d" ]]; then
    dbg="-d"
fi


dir="$(echo $wd)/build"
if [[ ! -e $dir ]]; then
    mkdir $dir
elif [[ ! -d $dir ]]; then
    echo "$dir already exists but is not a directory" 2>&2
fi
dir="$(echo $wd)/run"
if [[ ! -e $dir ]]; then
    mkdir $dir
elif [[ ! -d $dir ]]; then
    echo "$dir already exists but is not a directory" 2>&2
fi

./assemble "$assembly" "$(echo $wd)/build/memin.txt" "$(echo $wd)/build/diskin.txt" "$(echo $wd)/build/irq2in.txt"
if [ $? -ne 0 ]; then
    exit 2
fi
echo
echo "Program $assembly compiled successfully!"
echo "Running simulator..."
# echo "./simulate $wd/build/memin.txt $wd/build/diskin.txt $wd/build/irq2in.txt"
echo

if [[ -n $dbg ]]; then
    ./simulate \
        "$wd/build/memin.txt" \
        "$wd/build/diskin.txt" \
        "$wd/build/irq2in.txt" \
        "$wd/run/memout.txt" \
        "$wd/run/regout.txt" \
        "$wd/run/trace.txt" \
        "$wd/run/hwregtrace.txt" \
        "$wd/run/cycles.txt" \
        $dbg
else
    ./simulate \
        "$wd/build/memin.txt" \
        "$wd/build/diskin.txt" \
        "$wd/build/irq2in.txt"
fi

if [ $? -eq 0 ]; then
    echo "Simulation finished successfully!"
    exit 0
else
    exit 2
fi
