#!/bin/bash
# ./simulate memin.txt diskin.txt irq2in.txt [ memout.txt regout.txt trace.txt hwregtrace.txt cycles.txt -d ]
#-Wl,-z,stack-size=4194304
gcc -g -O0 -fsanitize=address Simulator/*.c -lX11 
rc=$?
if [ $rc -ne 0 ]; then
    echo "Error building simulator" 1>&2
    exit 1
fi
./a.out $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15}
rc=$?
if [ $rc -ne 0 ]; then
    echo "Simulation finished with errors" 1>&2
    exit 1
fi