#!/bin/bash
# ./simulate imemin.txt dmemin.txt diskin.txt irq2in.txt dmemout.txt regout.txt trace.txt hwregtrace.txt cycles.txt leds.txt display7seg.txt diskout.txt monitor.txt monitor.yuv
#-Wl,-z,stack-size=4194304
gcc Simulator/*.c
rc=$?
if [ $rc -ne 0 ]; then
    echo "Error building simulator"
    exit 1
fi
./a.out $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14}
rc=$?
if [ $rc -ne 0 ]; then
    echo "Simulation finished with errors"
    exit 1
fi