#!/bin/sh
# ssimpc stands for shraga's simp compiler
./assemble $1 imemin.txt dmemin.txt
rc=$?
if [ $rc -ne 0 ]; then
    echo "Error"
    exit 1
fi
./simulate imemin.txt dmemin.txt diskin.txt irq2in.txt dmemout.txt regout.txt trace.txt hwregtrace.txt cycles.txt leds.txt display7seg.txt diskout.txt monitor.txt monitor.yuv