#!/bin/sh
# ssimpc stands for shraga's simp compiler
./assemble $1 imemin.txt dmemin.txt
./simulate imemin.txt dmemin.txt diskin.txt irq2in.txt dmemout.txt regout.txt trace.txt hwregtrace.txt cycles.txt leds.txt display7seg.txt diskout.txt monitor.txt monitor.yuv